### ISSUE TITLE
Document using ASGI middleware with Ariadne ASGI app

### ISSUE THREAD

**Issue by salwator** [mirumee/ariadne#262] opened 2019-11-08 13:15 UTC
Ariadne ASGI app creates its own request on the way and loses all middleware as a side effect, ex. session information.

**Comment by patrys** [comment] 2019-11-12 10:57
I think everything already works as intended, can we close this issue?

**Comment by rafalp** [comment] 2019-11-12 11:36
@patrys This works as intended, but internal feedback I've gathered so far is negative - people coming from Django expect to use Starlette's middleware to set things on `request`, and then just access this `request` from within resolver and have the data they've set on it.

If anything, we should at least document this as gotcha and present idiomatic alternatives (eg. resolving this data in `context_value` factory).

**Comment by patrys** [comment] 2019-11-12 12:13
Setting things on request works as intended, changes are reflected in `scope` and picked up by the next request.

**Comment by rafalp** [comment] 2019-11-12 13:58
Ah, so those are available via `request.scope`? All-right then!

I'll keep this issue open to see if it makes sense to mention this in our docs sometime when I'll be  working on it.

**Comment by thebenwaters** [comment] 2019-12-29 14:22
Do you guys have a short tldr on how to do this?

**Comment by rafalp** [comment] 2019-12-29 14:31
Middlewares should use `request.scope` instead of `request` to store the data to be available from within the Ariadne.  When people use Starlette's [`AuthenticationMiddleware`](https://www.starlette.io/authentication/), they follow the docs and use `info.context["request"].user` within resolvers, which fails because `context["request"]` instance will be different request than one directly within Starlette. They should do `info.context["request"].scope["user"]"` instead.

This is known gotcha, and something we should document.

**Comment by thebenwaters** [comment] 2019-12-29 14:37
Ok this is great to know! I installed starlette and created an AuthBackend and attempted to install the middleware inside of the ariadne middleware

But I'm still getting the following error

```
{
  "data": null,
  "errors": [
    {
      "message": "AuthenticationMiddleware must be installed to access request.auth",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "hello"
      ],
      "extensions": {
        "exception": {
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/graphql/execution/execute.py\", line 625, in resolve_field_value_or_error",
            "    result = resolve_fn(source, info, **args)",
            "  File \"server/api/schema.py\", line 13, in resolve_hello",
            "    print(request.auth)",
            "  File \"starlette/requests.py\", line 116, in auth",
            "    ), \"AuthenticationMiddleware must be installed to access request.auth\"",
            "AssertionError: AuthenticationMiddleware must be installed to access request.auth"
          ],
          "context": {
            "self": "<starlette.re...t 0x10a4e3490>"
          }
        }
      }
    }
  ]
}

**Comment by rafalp** [comment] 2019-12-29 14:41
This is same thing. No middleware-specific attribute of `request` will work within the resolver. You need to use `context["request"] instance will be different request than one directly within Starlette. They should do info.context["request"].scope["auth"]` for this.

**Comment by patrys** [comment] 2020-01-07 15:37
To be clear, you only need to write changes to the `request.scope` object, it's safe to read from the `request` itself.

**Comment by shaozi** [comment] 2022-11-18 04:02
Any difference with uvcorn[standard] ?

**Closed** 2024-01-26 17:54 UTC
Labels: decision needed, docs
