### ISSUE TITLE
Django Async View in ariadne.contrib.django

### ISSUE THREAD

**Issue by dorianamouroux** [mirumee/ariadne#492] opened 2021-03-17 16:19 UTC
Hey 👋 

I noticed the Django integration of Ariadne is built using Sync Views: https://github.com/mirumee/ariadne/blob/master/ariadne/contrib/django/views.py#L35

Since Django 3.1, it's possible to declare [async views](https://docs.djangoproject.com/en/3.1/topics/async/#async-views), either with `async def my_view()` for a function view or declare `async def __call__` for a class view. 

I think it would be a good addition to Ariadne to also support Django async view, by creating `AsyncGraphQLView` and exporting it from `ariadne.contrib.django. The developer will still have the choice to use the sync or the async:

```python
from ariadne.contrib.django.views import GraphQLView, AsyncGraphQLView
from django.urls import path

from .schema import schema

urlpatterns = [
    ...
    path('graphql/', GraphQLView.as_view(schema=schema), name='graphql'),
    path('graphql-but-async/', AsyncGraphQLView.as_view(schema=schema), name='graphql'),
]
```

The developper should keep in mind that writing Async code in Django is still limited to few components, and should give a thorough read to https://docs.djangoproject.com/en/3.1/topics/async/

**Comment by rafalp** [comment] 2021-03-17 16:54
This is duplicate of `https://github.com/mirumee/ariadne/issues/450`, but thanks for making one more vote for async django views ;)

**Closed by rafalp** 2021-03-17 16:54 UTC
