### ISSUE TITLE
subscription.source is not working anymore in v0.10.0

### ISSUE THREAD

**Issue by vizo** [mirumee/ariadne#322] opened 2020-02-18 01:37 UTC
subscription.source is not working anymore in v0.10.0.
In v 0.9.0 it works.

Any clue?
Thanks

**Comment by rafalp** [comment] 2020-02-18 10:13
Duplicate of #320 

Please see [this comment](https://github.com/mirumee/ariadne/issues/320#issuecomment-586783800) for work around.

**Closed by rafalp** 2020-02-18 10:13 UTC
